theme: jekyll-theme-minimal
title: spy's homepage
description: If you're looking to support an independent operator focused on privacy, open-source development, and long-term ecosystem growth,
consider delegating to SPY.
